version: '3'

services:
  nginx:
    build: ./nginx
    ports:
      - ${CONFERO_PORT}:80
    depends_on:
      - couchdb
      - webserver
    volumes:
      - ./shared:/usr/shared
  couchdb:
    build: ./couchdb
    environment:
      - COUCHDB_USER=devuser
      - COUCHDB_PASSWORD=devpw
    ports:
      - 5984:5984
